title: Moses Yebei # your name (or website title) here
logo: "/images/aad65ff60c5c61a502de94519716d600.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst | Data SCientist | Machine Learning Engineer 
 <br><br>
  As a freelance data scientist, I translate data into valuable and comprehensible insights. My goal is to improve results, make the right decisions and save costs.
  
  I am experienced in machine learning, supervised and unsupervised algorithms and use data visualization techniques to present the results. I use Python, Streamlit and Tableau for my data projects. 
  <br><br>
  <a href="https://https://www.linkedin.com/in/moses-yebei-12996755/">Get in touch via</a> 
  <a href="https://https://www.linkedin.com/in/moses-yebei-12996755/">Get in touch via</a> 
  <a href="https://github.com/moses-y">View my GitHub profile</a>
  
theme: jekyll-theme-minimal
google_analytics: 314743619 # your Google Analytics tracking ID here
